[package]
name = "wroomd"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
axum.workspace = true
nix = { version = "0.30", features = ["net", "socket", "uio"] }
quinn-udp = "0.5"
socket2 = "0.6"
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wroom-edge.workspace = true
wroom-signaling.workspace = true
