[package]
name = "wroom-edge"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
aes = "0.8"
aes-gcm = "0.10"
crc = "3"
ctr = "0.10"
dimpl = "0.7"
hmac = "0.12"
rand = "0.9"
rcgen = "0.13"
sha1 = "0.10"
thiserror = "2"
tracing.workspace = true
wroom-core.workspace = true
