[package]
name = "wroom-signaling"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
axum.workspace = true
futures-util = "0.3"
prost.workspace = true
tokio.workspace = true
tracing.workspace = true
wroom-core.workspace = true

[build-dependencies]
prost-build.workspace = true
protoc-bin-vendored.workspace = true

[dev-dependencies]
bytes = "1"
tokio-tungstenite = "0.28"
